FROM oven/bun:latest

WORKDIR /app

RUN apt-get update && apt-get install -y --no-install-recommends \
    ca-certificates \
    curl \
    && rm -rf /var/lib/apt/lists/*

RUN apt-get update && apt-get install -y --no-install-recommends \
    ffmpeg \
    yt-dlp \
    && rm -rf /var/lib/apt/lists/*

COPY app/provider ./app/provider

CMD ["/bin/bash", "-lc", "exec bun run app/provider/index.ts"]
